### ISSUE TITLE
No way to hide 'View on github'

### ISSUE THREAD

**Issue by utdrmac** [pages-themes/tactile#7]
Our repository is private; only gh-pages are public. Thus "View on GitHub" buttons are pointless; send you to 404 not found. How can these be not displayed?

**Comment by benbalter** [comment]
@utdrmac would you be interested in submitting a pull request to wrap https://github.com/pages-themes/tactile/blob/5e8a1a89d0d58c52fa5e456cac8c3ad01988abae/_layouts/default.html#L29-L33 in a `if site.github.public` conditional?

**Comment by utdrmac** [comment]
That would probably be a preferred method. I "hacked" it by adding some custom CSS to just hide the a#view-on-github elements.
